name: Influx3_Telegraf
services:

  influxdb3-init:
    image: influxdb:3.6.0-core
    container_name: influxdb3-init
    user: root
    command:
      - sh
      - -c
      - |
        mkdir -p /var/lib/influxdb3/data /var/lib/influxdb3/plugins && \
        chown -R influxdb3:influxdb3 /var/lib/influxdb3
    volumes:
      - influxdb3-data:/var/lib/influxdb3/data
      - influxdb3-plugins:/var/lib/influxdb3/plugins
    restart: "no"

  influxdb3-core:
    container_name: influxdb3-core
    image: influxdb:3.6.0-core
    ports:
      - 8181:8181
    environment:
      - INFLUXDB3_ADMIN_TOKEN_FILE=run/secrets/influxdb_admin_token
      - INFLUXDB3_DATABASE_NAME=${INFLUX_DB_NAME}
      - TZ=America/Mexico_City
    depends_on:
      influxdb3-init:
        condition: service_completed_successfully
    user: influxdb3
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --plugin-dir=/var/lib/influxdb3/plugins
    # Volumenes bind, cambiar a tipo named
    # para que asi docker los administre
    volumes:
      - influxdb3-data:/var/lib/influxdb3/data
      - influxdb3-plugins:/var/lib/influxdb3/plugins
    secrets:
      - influxdb_admin_token
    networks:
      - iot-network

  explorer:
    image: influxdata/influxdb3-ui:1.4.0
    container_name: influxdb3-explorer
    command: ["--mode=admin"]
    ports:
      - "8888:80"
    volumes:
      - ./influxdb/config:/app-root/config:ro
    restart: unless-stopped
    networks:
      - iot-network

  telegraf:
    image: telegraf:1.36.3
    container_name: telegraf
    environment:
      MQTT_BROKER: ${MQTT_BROKER_URL}
      # Configuration output pluguin v2 to write on influxdb3
      INFLUX_SERVICE: influxdb3-core
      INFLUX_PORT: 8181
      DATABASE_NAME: ${INFLUX_DB_NAME}
    secrets:
      - influxdbtoken_telegraf
      - mqtt_broker
      - mqtt_user
      - mqtt_pass
    user: "${USERID}"
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb3-core
    restart: always
    networks:
      - iot-network

networks:
  iot-network:
    driver: bridge

volumes:
  influxdb3-data:
  influxdb3-plugins:

secrets:
  influxdb_admin_token:
    file: ./secrets/influxdb_admin_token.env
  influxdbtoken_telegraf:
    file: ./secrets/influxdbtoken_telegraf.env
  mqtt_broker:
    file: ./secrets/mqtt_broker.env
  mqtt_user:
    file: ./secrets/mqtt_user.env
  mqtt_pass:
    file: ./secrets/mqtt_pass.env