[agent]
  interval = "3s"
  round_interval = true
  debug = true

# [[secretstores.docker]]
#   id = "docker_store"
#   # path = "/run/secrets"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb3-core:8181"]
  # ----------------------------
  # For DEV use direct env vars
  token = "${INFLUX_TOKEN}"
  # token = "@{docker_store:influxdbtoken_telegraf}"
  organization = "ignored"
  bucket = "main"

# Configuration of the host
# [[inputs.cpu]]
#   percpu = true
#   totalcpu = true
#   report_active = true

# [[inputs.mem]]
# [[inputs.disk]]
# [[inputs.system]]

# ************************************
# MQTT CONSUMER
# ************************************
[[inputs.mqtt_consumer]]
  ## MQTT broker URLs to be used. The format should be scheme://host:port,
  ## schema can be tcp, ssl, or ws.
  servers = ["${MQTT_BROKER}"]

  # infraMonitor/status/isInternet
  topics = ["pico01/#", "pico02/#"]
  qos = 0

  ## Username and password to connect MQTT server.
  # For dev use direct env vars
  #--------------------------
  username = "${MQTT_USER}"
  password = "${MQTT_PASS}"
  # username = "@{docker_store:mqtt_user}"
  # password = "@{docker_store:mqtt_pass}"
  data_format = "value"
  data_type = "float"

[[inputs.mqtt_consumer]]
  ## MQTT broker URLs to be used. The format should be scheme://host:port,
  ## schema can be tcp, ssl, or ws.
  servers = ["${MQTT_BROKER}"]

  topics = ["hardwareInfra/assets/mikrotik/data"]
  qos = 0
  username = "${MQTT_USER}"
  password = "${MQTT_PASS}"
  data_format = "json_v2"

  [[inputs.mqtt_consumer.topic_parsing]]
    topic = "+/+/+/+"
    tags = "project/definition/asset/scope"

  [[inputs.mqtt_consumer.json_v2]]
    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "assetName"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "status_int"
      type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "packet_loss"
      type = "float"
